app = "fratrat-relay"
primary_region = "ord"

[[services]]
internal_port = 9000
protocol = "tcp"

[[services.ports]]
port = 9000

[[services]]
internal_port = 9001
protocol = "tcp"

[[services.ports]]
port = 9001

[mounts]
source = "relay_data"
destination = "/data"

[build]
dockerfile = "controller/Containerfile"
