FROM rust:1 as build
WORKDIR /opt/zrp

RUN apt-get update -y
RUN apt-get install protobuf-compiler -y

COPY . .

RUN cargo build --release -p controller

FROM gcr.io/distroless/cc-debian13:latest
RUN useradd -r -s /bin/false -d /data zkrp
COPY --from=builder /build/target/release/controller /usr/local/bin/relay
USER zkrp
ENTRYPOINT ["/usr/local/bin/relay"]
