FROM rust:1 as build
WORKDIR /opt/zrp

COPY . .

RUN cargo build --release

FROM gcr.io/distroless/cc-debian13:latest
COPY --from=build /opt/zrp/target/release/controller /
ENTRYPOINT [ "/controller" ]
